### ISSUE TITLE
IC-3 query

### ISSUE THREAD

**Issue by PaulZH** [Swirrl/rdf-validator#17]
I see that you want to capture the subproperties of qb:componentProperty without relying on reasoning.
What happens now is that the subquery finds all instances for ?cp, in our case 5 instances. All those instances are injected in the filter and I get 4 times NOT exist while the 5th one qb:measure exists. We get a fail while there is a MeasureProperty.

I think this query is safer.
`WHERE
 {
  ?dsd a qb:DataStructureDefinition .
  ?dsd qb:component [?property [a qb:MeasureProperty]].
  FILTER (!(EXISTS{?property rdfs:subPropertyOf+ qb:componentProperty} || ?property = qb:componentProperty))
}`

**Comment by jennet** [comment]
Moved to https://github.com/Swirrl/data-cube-validations/issues/7

**Comment by Robsteranium** [comment]
Thanks @PaulZH, sorry it's taken us so long to respond!

The suggested change doesn't seem to work on our data, it yields DSDs which do have measures.

It might be that your problem with the original query is actually that it's [looking for the qb:MeasureType dimension](https://github.com/Swirrl/pmd-rdf-validations/blob/master/pmd-qb/src/swirrl/validations/pmd-qb/03_SELECT_DSD_Has_At_Least_1_Measure.sparql#L20) instead of a measure property. Thus it would erroneously pass measures-dimensions cubes without measures and fail cubes with single- or multi-measure observations.

I think we instead want something like this:

```sparql
PREFIX rdfs:    <http://www.w3.org/2000/01/rdf-schema#>
PREFIX qb:      <http://purl.org/linked-data/cube#>

SELECT ?dsd WHERE {
  ?dsd a qb:DataStructureDefinition .
  
  FILTER NOT EXISTS {
    # qb:measure and other alternatives
    ?component_attachment rdfs:subPropertyOf* qb:componentProperty .
    ?dsd qb:component [?component_attachment ?measure] .
    ?measure a qb:MeasureProperty .
  }
}
```

This is looking for measure properties regardless of how they've been attached to their respective component specification.
